In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
mobile_data = pd.read_csv('https://github.com/sukhioo7/dataset/blob/main/Mobile%20Price%20Classification/train.csv?raw=true')
mobile_data.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [ ]:
X = mobile_data.drop('price_range',axis=1)
Y = mobile_data['price_range']

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=101)

NameError: name 'X' is not defined

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=4)

In [ ]:
knn_model.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=4)

In [ ]:
predictions = knn_model.predict(X_test)
predictions

array([1, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 3, 0,
       2, 3, 2, 2, 2, 2, 0, 0, 2, 3, 0, 0, 3, 0, 0, 0, 1, 1, 1, 2, 3, 2,
       3, 1, 1, 3, 3, 1, 0, 0, 2, 2, 3, 2, 0, 3, 2, 3, 2, 2, 3, 1, 3, 1,
       0, 0, 0, 1, 1, 2, 3, 2, 1, 3, 3, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 1,
       0, 0, 3, 2, 0, 2, 0, 3, 2, 0, 2, 3, 0, 1, 2, 3, 0, 2, 0, 0, 2, 0,
       1, 0, 3, 2, 2, 2, 1, 3, 1, 0, 3, 3, 2, 3, 1, 3, 3, 2, 1, 1, 1, 0,
       0, 1, 0, 2, 3, 0, 2, 3, 1, 3, 0, 0, 0, 1, 1, 2, 2, 0, 3, 1, 2, 2,
       3, 2, 2, 0, 3, 2, 2, 2, 2, 2, 1, 2, 1, 1, 3, 3, 1, 2, 0, 3, 1, 3,
       2, 2, 3, 2, 2, 1, 0, 1, 2, 2, 2, 2, 0, 3, 1, 0, 2, 2, 0, 2, 0, 0,
       3, 0, 0, 1, 3, 2, 1, 3, 0, 3, 2, 2, 1, 2, 1, 3, 1, 3, 0, 0, 3, 1,
       1, 2, 3, 0, 2, 3, 3, 0, 3, 1, 1, 1, 0, 2, 1, 2, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 3, 3, 2, 3, 3, 1, 2, 1, 1, 3, 1, 0, 2, 0, 0, 1, 3, 3, 0,
       1, 0, 2, 1, 0, 2, 3, 0, 3, 2, 1, 2, 1, 2, 1, 2, 2, 3, 1, 2, 2, 2,
       2, 1, 2, 3, 2, 3, 0, 1, 1, 0, 2, 1, 0, 2, 3,

In [ ]:
X_test

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
1458           1368     0          0.5         0  10       1          42   
198             609     0          0.5         0   3       0          26   
1276            586     0          1.4         1  10       1           8   
1243           1180     1          1.2         0   5       1          50   
1267            896     0          1.0         1   3       1           4   
...             ...   ...          ...       ...  ..     ...         ...   
257             507     1          0.5         1   1       0          32   
1020           1119     0          0.5         1   0       1          23   
1057            980     1          0.5         0   0       1          33   
1230            697     0          2.7         1   5       1          20   
510             687     1          1.3         0   9       1          50   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
1458    0.2         91        1  20        907       925  1590    12     0   
198     0.3         93        4   4        938      1948  1866    11    10   
1276    0.5        142        8  14        116       598  3178     9     7   
1243    1.0        144        4  20        925      1252  1464     7     3   
1267    0.3        111        1   4       1379      1469  1060    12    10   
...     ...        ...      ...  ..        ...       ...   ...   ...   ...   
257     0.5        141        7  11        936      1398  1702    17     0   
1020    0.4        164        4   1        821       915  3520     7     4   
1057    0.9        160        6   0       1008      1758  2268     7     5   
1230    0.4        173        2   6        478      1477   259    12     6   
510     0.6        151        4  20        584      1151  3416    14     6   

      talk_time  three_g  touch_screen  wifi  
1458         14        1             0     0  
198          14        1             1     1  
1276         10        1             0     1  
1243         20        1             1     1  
1267          4        1             1     1  
...         ...      ...           ...   ...  
257           5        1             1     1  
1020          7        1             0     0  
1057          4        1             1     0  
1230          4        1             1     1  
510           8        1             1     0  

[400 rows x 20 columns]

In [ ]:
Y_test

1458    1
198     1
1276    2
1243    1
1267    1
       ..
257     1
1020    3
1057    2
1230    0
510     3
Name: price_range, Length: 400, dtype: int64

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(predictions,Y_test))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        96
           1       0.90      0.88      0.89       105
           2       0.92      0.92      0.92       120
           3       0.93      0.99      0.96        79

    accuracy                           0.93       400
   macro avg       0.93      0.93      0.93       400
weighted avg       0.92      0.93      0.92       400



In [ ]:
print(confusion_matrix(predictions,Y_test))

[[ 90   6   0   0]
 [  4  92   9   0]
 [  0   4 110   6]
 [  0   0   1  78]]


In [ ]:
error = []

for k in range(5,50):
  knn_model = KNeighborsClassifier(n_neighbors=k)
  knn_model.fit(X_train,Y_train)
  predictions = knn_model.predict(X_test)
  e = np.mean(predictions != Y_test)
  error.append(e)


In [ ]:
error

[0.0625,
 0.07,
 0.07,
 0.0775,
 0.07,
 0.0675,
 0.0725,
 0.07,
 0.07,
 0.075,
 0.075,
 0.0725,
 0.075,
 0.075,
 0.0675,
 0.0725,
 0.0675,
 0.075,
 0.065,
 0.08,
 0.07,
 0.0725,
 0.07,
 0.07,
 0.065,
 0.07,
 0.075,
 0.07,
 0.0725,
 0.0725,
 0.0725,
 0.07,
 0.075,
 0.075,
 0.0775,
 0.0725,
 0.08,
 0.075,
 0.075,
 0.0825,
 0.085,
 0.0775,
 0.085,
 0.085,
 0.0825]